#pragma once

#define CIRCUITLM_BOARD_WAVESHARE_S3_TOUCH_AMOLED_18 101
#define CIRCUITLM_BOARD_ESP32_S3_GENERIC_16M8M 102
#define CIRCUITLM_BOARD_ESP32_S2_GENERIC_4M2M 201
#define CIRCUITLM_BOARD_ESP32_C3_GENERIC 301
#define CIRCUITLM_BOARD_ESP32_C6_GENERIC 401
#define CIRCUITLM_BOARD_ESP32_P4_GENERIC 501

#define CIRCUITLM_DISPLAY_NONE 0
#define CIRCUITLM_DISPLAY_OLED_196_I2C 11
#define CIRCUITLM_DISPLAY_SPI_292 12
#define CIRCUITLM_DISPLAY_AMOLED_196 13
#define CIRCUITLM_DISPLAY_AMOLED_196_TOUCH 14
#define CIRCUITLM_DISPLAY_AMOLED_18_TOUCH 15

#define CIRCUITLM_MIC_NONE 0
#define CIRCUITLM_MIC_MODULINO 21
#define CIRCUITLM_MIC_GENERIC_I2S 22

#define CIRCUITLM_SPEAKER_NONE 0
#define CIRCUITLM_SPEAKER_MINI_I2S 31
#define CIRCUITLM_SPEAKER_EXTERNAL_I2S 32

#ifndef CIRCUITLM_BOARD
#error "Select CIRCUITLM_BOARD before including circuitlm_config.h"
#endif
#ifndef CIRCUITLM_DISPLAY
#define CIRCUITLM_DISPLAY CIRCUITLM_DISPLAY_NONE
#endif
#ifndef CIRCUITLM_MIC
#define CIRCUITLM_MIC CIRCUITLM_MIC_NONE
#endif
#ifndef CIRCUITLM_SPEAKER
#define CIRCUITLM_SPEAKER CIRCUITLM_SPEAKER_NONE
#endif

#if CIRCUITLM_BOARD == CIRCUITLM_BOARD_WAVESHARE_S3_TOUCH_AMOLED_18
#define CIRCUITLM_TARGET_ESP32S3 1
#define CIRCUITLM_TIER_FULL 1
#define CIRCUITLM_FLASH_MB 16
#define CIRCUITLM_PSRAM_MB 8
#elif CIRCUITLM_BOARD == CIRCUITLM_BOARD_ESP32_S3_GENERIC_16M8M
#define CIRCUITLM_TARGET_ESP32S3 1
#define CIRCUITLM_TIER_FULL 1
#define CIRCUITLM_FLASH_MB 16
#define CIRCUITLM_PSRAM_MB 8
#elif CIRCUITLM_BOARD == CIRCUITLM_BOARD_ESP32_S2_GENERIC_4M2M
#define CIRCUITLM_TARGET_ESP32S2 1
#define CIRCUITLM_TIER_COMPACT 1
#define CIRCUITLM_FLASH_MB 4
#define CIRCUITLM_PSRAM_MB 2
#elif CIRCUITLM_BOARD == CIRCUITLM_BOARD_ESP32_C3_GENERIC
#define CIRCUITLM_TARGET_ESP32C3 1
#define CIRCUITLM_TIER_MICRO 1
#define CIRCUITLM_FLASH_MB 4
#define CIRCUITLM_PSRAM_MB 0
#elif CIRCUITLM_BOARD == CIRCUITLM_BOARD_ESP32_C6_GENERIC
#define CIRCUITLM_TARGET_ESP32C6 1
#define CIRCUITLM_TIER_MICRO 1
#define CIRCUITLM_FLASH_MB 4
#define CIRCUITLM_PSRAM_MB 0
#elif CIRCUITLM_BOARD == CIRCUITLM_BOARD_ESP32_P4_GENERIC
#define CIRCUITLM_TARGET_ESP32P4 1
#define CIRCUITLM_TIER_FULL 1
#define CIRCUITLM_FLASH_MB 16
#define CIRCUITLM_PSRAM_MB 16
#else
#error "Unknown CircuitLM board profile"
#endif

#if defined(CIRCUITLM_TIER_MICRO) && defined(CIRCUITLM_MODEL_FULL)
#error "The full CircuitLM model requires a full-tier board profile"
#endif
