#!/usr/bin/env python3
"""Build the bounded CircuitLM ESP32 pilot corpus and C prompt tables."""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import re
from pathlib import Path

from tokenizers import Tokenizer


TASKS = ("explain", "symbol", "behavior", "game")
QUESTION = {
    "explain": "Explain what this is to a child in one short sentence.",
    "symbol": "Explain only how its circuit symbol looks in one short sentence.",
    "behavior": "Explain only how it works in one short sentence.",
    "game": "Create one exciting mission clue without saying the component name.",
}


def prompt(record: dict, task: str) -> str:
    if task == "game":
        return (
            "Circuit Quest offline game\n"
            "Task: live mission clue\n"
            f"Name: {record['name']}\n"
            f"Purpose: {record['purpose']}\n"
            f"Behavior: {record['behavior']}\n"
            "Rule: Make one exciting clue. Never reveal the name.\n"
            "Clue:"
        )
    fact_key = {"explain": "purpose", "symbol": "symbol", "behavior": "behavior"}[task]
    return (
        "Circuit Heroes offline electronics pilot\n"
        f"Task: {task}\n"
        f"Name: {record['name']}\n"
        f"Type: {record['family']}\n"
        f"Fact: {record[fact_key]}\n"
        f"Question: {QUESTION[task]}\n"
        "Answer:"
    )


def answers(record: dict, task: str) -> list[str]:
    name = record["name"]
    if task == "explain":
        return [
            f"{name} {record['purpose']}.",
            f"A {name} {record['purpose']}.",
            f"This is a {name}. It {record['purpose']}.",
        ]
    if task == "symbol":
        return [
            f"The {name} symbol looks like {record['symbol']}.",
            f"Look for {record['symbol']}; that is the {name} symbol.",
        ]
    if task == "behavior":
        return [
            f"A {name} works like this: {record['behavior']}.",
            f"Inside its job, {record['behavior']}.",
        ]
    return [
        f"Mission alert! Find the hero that {record['purpose']}.",
        f"Circuit Quest: choose the part that {record['purpose']}.",
        f"Power problem! Which component {record['purpose']}?",
        f"Mystery round! Pick the hero where {record['behavior']}.",
    ]


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def c_ident(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", value).upper()


def write_jsonl(path: Path, records: list[dict], seed: int) -> dict:
    rows = []
    for component_index, component in enumerate(records):
        for task in TASKS:
            for answer in answers(component, task):
                for wording in range(12):
                    rows.append({
                        "schema": "circuitlm-pilot-instruction-v1",
                        "task": task,
                        "component_index": component_index,
                        "component": component["name"],
                        "prompt": prompt(component, task),
                        "answer": answer,
                        "verified_facts": component,
                        "wording_variant": wording,
                    })
    rng = random.Random(seed)
    rng.shuffle(rows)
    paths = {}
    for split, bounds in {"train": (0, 80), "validation": (80, 90), "test": (90, 100)}.items():
        selected = [row for row in rows if int.from_bytes(
            hashlib.sha256(f"{row['component']}:{row['task']}:{row['wording_variant']}".encode()).digest()[:4],
            "little") % 100 in range(*bounds)]
        output = path / f"{split}.jsonl"
        output.write_text("".join(json.dumps(row, ensure_ascii=False) + "\n" for row in selected))
        paths[split] = len(selected)
    return paths


def write_header(path: Path, records: list[dict], tokenizer: Tokenizer) -> dict:
    ids: list[int] = []
    offsets = [0]
    max_prompt = 0
    for record in records:
        for task in TASKS:
            encoded = tokenizer.encode(prompt(record, task)).ids
            max_prompt = max(max_prompt, len(encoded))
            ids.extend(encoded)
            offsets.append(len(ids))
    header = path / "circuitlm_pilot_data.h"
    with header.open("w", encoding="utf-8") as out:
        out.write("// Generated by tools/build_pilot.py. Do not edit.\n#pragma once\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("typedef struct { const char *id, *name, *family, *purpose, *symbol, *behavior, *safety, *anchors; } circuitlm_pilot_record_t;\n")
        out.write(f"#define CIRCUITLM_PILOT_RECORD_COUNT {len(records)}u\n")
        out.write(f"#define CIRCUITLM_PILOT_TASK_COUNT {len(TASKS)}u\n")
        out.write("enum { CIRCUITLM_PILOT_EXPLAIN, CIRCUITLM_PILOT_SYMBOL, CIRCUITLM_PILOT_BEHAVIOR, CIRCUITLM_PILOT_GAME };\n\n")
        out.write("static const circuitlm_pilot_record_t CIRCUITLM_PILOT_RECORDS[] = {\n")
        for r in records:
            fields = [r[k] for k in ("id", "name", "family", "purpose", "symbol", "behavior", "safety")]
            fields.append("|".join(r["anchors"]))
            out.write("    {" + ",".join(c_string(v) for v in fields) + "},\n")
        out.write("};\n\n")
        out.write(f"static const uint16_t CIRCUITLM_PILOT_PROMPT_OFFSETS[{len(offsets)}] = {{\n    ")
        out.write(",".join(str(v) for v in offsets))
        out.write("\n};\n")
        out.write(f"static const uint16_t CIRCUITLM_PILOT_PROMPT_IDS[{len(ids)}] = {{\n    ")
        for index, value in enumerate(ids):
            if index and index % 24 == 0:
                out.write("\n    ")
            out.write(f"{value},")
        out.write("\n};\n")
    return {"prompt_tokens": len(ids), "max_prompt_tokens": max_prompt, "header": header.name}


def main() -> None:
    parser = argparse.ArgumentParser()
    root = Path(__file__).resolve().parents[1]
    parser.add_argument("--hil", type=Path, default=root / "pilot" / "hil_v0_1.json")
    parser.add_argument("--tokenizer", type=Path, default=root / "model-tokenizer.json")
    parser.add_argument("--output", type=Path, default=root / "generated" / "pilot")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    document = json.loads(args.hil.read_text())
    records = document["components"]
    if not 40 <= len(records) <= 64 or len({r["id"] for r in records}) != len(records):
        raise SystemExit("pilot HIL must contain 40 to 64 uniquely identified components")
    for record in records:
        if len(record.get("anchors", [])) < 2:
            raise SystemExit(f"{record['id']} needs at least two verifier anchors")
    args.output.mkdir(parents=True, exist_ok=True)
    tokenizer = Tokenizer.from_file(str(args.tokenizer))
    split_counts = write_jsonl(args.output, records, args.seed)
    header_stats = write_header(args.output, records, tokenizer)
    manifest = {
        "schema": document["schema"],
        "review_status": document["review_status"],
        "license": document["license"],
        "component_count": len(records),
        "tasks": list(TASKS),
        "splits": split_counts,
        "hil_sha256": hashlib.sha256(args.hil.read_bytes()).hexdigest(),
        **header_stats,
    }
    (args.output / "pilot-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
