#!/usr/bin/env python3
"""Validate a CircuitLM hardware selection and generate a C header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "config" / "hardware_profiles.json"


def select(items: dict, name: str, kind: str) -> dict:
    try:
        return items[name]
    except KeyError as exc:
        choices = ", ".join(sorted(items))
        raise SystemExit(f"unknown {kind} {name!r}; choose one of: {choices}") from exc


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--board")
    parser.add_argument("--display", default=None)
    parser.add_argument("--mic", default="none")
    parser.add_argument("--speaker", default="none")
    parser.add_argument("--model-tier", choices=("full", "compact", "micro"), default=None)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--list", action="store_true")
    args = parser.parse_args()

    registry = json.loads(REGISTRY.read_text())
    if args.list:
        for group in ("boards", "displays", "microphones", "speakers"):
            print(f"{group}:")
            for name in sorted(registry[group]):
                print(f"  {name}")
        return
    if not args.board or not args.output:
        parser.error("--board and --output are required unless --list is used")

    board = select(registry["boards"], args.board, "board")
    display_name = args.display if args.display is not None else board["display"]
    display = select(registry["displays"], display_name, "display")
    mic = select(registry["microphones"], args.mic, "microphone")
    speaker = select(registry["speakers"], args.speaker, "speaker")
    model_tier = args.model_tier or board["tier"]
    rank = {"micro": 0, "compact": 1, "full": 2}
    if rank[model_tier] > rank[board["tier"]]:
        raise SystemExit(
            f"{args.board} is a {board['tier']} board and cannot run a {model_tier} model"
        )

    content = (
        "// Generated by CircuitLM Kit. Do not edit.\n"
        "#pragma once\n"
        '#include "circuitlm_config_base.h"\n'
        f"#define CIRCUITLM_BOARD {board['macro']}\n"
        f"#define CIRCUITLM_DISPLAY {display['macro']}\n"
        f"#define CIRCUITLM_MIC {mic['macro']}\n"
        f"#define CIRCUITLM_SPEAKER {speaker['macro']}\n"
        f"#define CIRCUITLM_MODEL_{model_tier.upper()} 1\n"
        f'#define CIRCUITLM_IDF_TARGET "{board["target"]}"\n'
    )
    # The base must be included after selections so its validation sees them.
    content = content.replace('#include "circuitlm_config_base.h"\n', "") + (
        '#include "circuitlm_config_base.h"\n'
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    base_source = ROOT / "config" / "circuitlm_config_base.h"
    if not base_source.is_file():
        base_source = ROOT / "include" / "circuitlm_config_base.h"
    base_target = args.output.parent / "circuitlm_config_base.h"
    base_target.write_text(base_source.read_text())
    print(
        f"wrote {args.output}: board={args.board}, display={display_name}, "
        f"mic={args.mic}, speaker={args.speaker}, model={model_tier}; "
        f"copied {base_target.name}"
    )


if __name__ == "__main__":
    main()
